### ISSUE TITLE
State is not reactive

### ISSUE THREAD

**Issue by nikitavoloboev** [codemask-labs/stan-js#74]
<img width="664" alt="image" src="https://github.com/codemask-labs/stan-js/assets/6391776/97b8edc8-132b-4646-a2d1-836b0cc4ab4e">

<img width="613" alt="image" src="https://github.com/codemask-labs/stan-js/assets/6391776/e18bb297-b9ee-428f-b8fa-2d010723cb2d">

when I press the button, the state does not update, not sure why

**Comment by nikitavoloboev** [comment]
<img width="955" alt="image" src="https://github.com/codemask-labs/stan-js/assets/6391776/d5d5a381-c3d3-411c-9606-4f83647a9508">

this fails to update too, just tested

**Comment by jpudysz** [comment]
@nikitavoloboev you can't use stan-js like that. You're mixing non React functions with React. Let me explain:

1. Define your store out of the React component:

```ts
// store.ts
const { useStore } = createStore({
  focusedInput: "'',
  name: "",
  // other props
｝）

// now, export useStore for React components

export {
    useStore
}
```

From now on you can import this hook in any component in your app and update it with actions:

```tsx
const MyComponent = () => {
  // import from here action prefixed with `set`
  const { setName } = useStore()
 
  return (
      <button onClick={() => setName('after update'))>Update the name</button>
  )
}
```

**Comment by Brentlok** [comment]
You can check our examples section for more detailed code:
https://codemask-labs.github.io/stan-js/examples/react/

**Comment by jpudysz** [comment]
Also, if you destructure `name`, your component will auto-subscribe to the updates:

1. This won't re-render `MyComponent` as you didn't subscribe
```tsx
const MyComponent = () => {
  const { setName } = useStore()
 
  return (
      <button onClick={() => setName('after update'))>Update the name</button>
  )
}
```

2. This re-render `MyComponent` as you subscribed
```tsx
const MyComponent = () => {
  // auto-subscribe
  const { name, setName } = useStore()
 
  return (
      <div>
        <button onClick={() => setName('after update'))>Update the name</button>
        <div>{name}</div>
      </div>
  )
}
```

**Comment by nikitavoloboev** [comment]
> 1. Define your store out of the React component

I can't do this though because each route requires certain amount of data

I thought of defining the store at each of the client components.

And passing state down because I can't rely on global state of the store as each route has different fetch query at the top of react server component if that makes sense.

**Comment by jpudysz** [comment]
> I thought of defining the store at each of the client components.

You can define many stores, just don't do this inside the component.

**Comment by Brentlok** [comment]
In that case you can use `Scoped Store`, we even have [Next.js SSR example](https://codemask-labs.github.io/stan-js/examples/nextjs/)

**Comment by Brentlok** [comment]
Hi @nikitavoloboev, were you able to fix your issue?
